language: java
jdk:
  - oraclejdk8
  - oraclejdk7

sudo: required

install: true

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
after_success:
  - mvn clean install
  - mvn test


notifications:
  email:
    recipients:
      - aivaras.silale@gmail.com
    on_success: never # default: change
    on_failure: always # default: always