os:
  - linux
#  - osx

language: java
jdk:
  - oraclejdk7
  - oraclejdk8

sudo: required

install: true


script:
  - java -version
  - mvn test
#after_success:

notifications:
  email:
    recipients:
      - aivaras.silale@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
